//////user/////
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GOOGLE_SIGN_IN_START='GOOGLE_SIGN_IN_START';
export const EMAIL_SIGN_IN_START='EMAIL_SIGN_IN_START';
export const SIGN_IN_SUCCESS='SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL='SIGN_IN_FAIL';
export const CHECK_USER_SESSION='CHECK_USER_SESSION';

export const SIGN_OUT_START='SIGN_OUT_START';
export const SIGN_OUT_SUCCESS='SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAIL='SIGN_OUT_FAIL';



//////cart////
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM_TO_CART='ADD_ITEM_TO_CART';
export const CLEAR_ITEM_FROM_CART='CLEAR_ITEM_FROM_CART';
export const REMOVE_ITEM_FROM_CART='REMOVE_ITEM_FROM_CART';


///shop////

export const FETCH_COLLECTIONS_START='FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS='FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAIL='FETCH_COLLECTIONS_FAIL';