//////user/////
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//////cart////
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const ADD_ITEM_TO_CART='ADD_ITEM_TO_CART';
export const CLEAR_ITEM_FROM_CART='CLEAR_ITEM_FROM_CART';
export const REMOVE_ITEM_FROM_CART='REMOVE_ITEM_FROM_CART';


///shop////

export const FETCH_COLLECTIONS_START='FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS='FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAIL='FETCH_COLLECTIONS_FAIL';